/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
static yyconst short int yy_acclist[167] =
    {   0,
       79,   77,   78,    7,   77,   78,    6,   78,   37,   77,
       78,   66,   77,   78,   33,   77,   78,   38,   77,   78,
       65,   77,   78,   46,   77,   78,   47,   77,   78,   31,
       77,   78,   29,   77,   78,   43,   77,   78,   30,   77,
       78,   50,   77,   78,   32,   77,   78,   55,   77,   78,
       56,   77,   78,   52,   77,   78,   42,   77,   78,   34,
       77,   78,   36,   77,   78,   35,   77,   78,   51,   77,
       78,   76,   77,   78,   48,   77,   78,   49,   77,   78,
       40,   77,   78,   44,   77,   78,   39,   77,   78,   45,
       77,   78,   41,   77,   78,    4,   78,    3,   78,    4,

       78,   75,   78,   74,   78,   67,   78,   78,    7,   21,
       14,   22,   15,   65,   12,   24,   10,   25,   11,   26,
       58,    1,   13,   57,   54,   62,   56,   27,   18,   20,
       19,   28,   76,   17,   16,   23,    2,   75,   73,   72,
       73,   71,   73,   68,   73,   70,   73,   69,   73,   65,
       63,   61,    5,   57,   60,   62,   59,   53,    8,    9,
       65,   64,   61,   58,   60,   57
    } ;

static yyconst short int yy_accept[108] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   15,   18,   21,   24,   27,   30,   33,   36,
       39,   42,   45,   48,   51,   54,   57,   60,   63,   66,
       69,   72,   75,   78,   81,   84,   87,   90,   93,   96,
       98,  100,  102,  104,  106,  108,  109,  110,  111,  112,
      113,  114,  115,  115,  116,  117,  118,  119,  120,  121,
      122,  123,  123,  124,  125,  126,  127,  127,  128,  129,
      130,  131,  132,  133,  134,  135,  136,  137,  138,  139,
      140,  142,  144,  146,  148,  150,  151,  152,  152,  153,
      153,  154,  155,  156,  157,  158,  159,  160,  161,  162,

      163,  163,  164,  165,  166,  167,  167
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   28,   27,   27,
       29,   30,   31,   32,   27,    1,   33,   33,   25,   25,

       26,   33,   27,   27,   27,   27,   27,   27,   27,   34,
       27,   27,   27,   35,   27,   36,   27,   37,   27,   28,
       27,   27,   38,   39,   40,   41,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    6,    1,    1,
        1,    1,    1,    1,    6,    6,    6,    6,    1,    3,
        1,    1,    5,    5,    5,    5,    5,    1,    1,    1,
        1
    } ;

static yyconst short int yy_base[119] =
    {   0,
        0,    0,   39,   40,   41,   42,  153,  215,  150,  215,
      129,  215,  128,   41,  119,  215,  215,  126,   37,  215,
       38,   36,   46,   49,   61,  215,  215,   34,  124,   47,
      215,    0,  215,  215,  123,  215,   43,  215,  215,  215,
      215,  122,    0,  215,  215,   68,  123,  215,  215,  215,
      215,   50,    0,  215,  215,  215,  215,  215,  215,   66,
      215,  105,  215,   68,   73,   83,   88,   92,   71,  215,
      215,  215,   67,    0,  215,  215,  215,  215,    0,  215,
      215,  215,  215,  215,  215,   66,  215,    0,  105,   78,
      215,   94,  112,   98,  110,  114,  215,  215,  125,  215,

        0,  117,  119,  124,  126,  215,  155,  161,  167,  169,
      175,  181,  187,  191,  196,  202,  206,  209
    } ;

static yyconst short int yy_def[119] =
    {   0,
      106,    1,  107,  107,  108,  108,  106,  106,  106,  106,
      106,  106,  106,  106,  109,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  110,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  111,  106,  106,  112,  106,  106,  106,  106,
      106,  113,  114,  106,  106,  106,  106,  106,  106,  106,
      106,  115,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  110,  106,  106,  106,  106,  111,  106,
      106,  106,  106,  106,  106,  116,  106,  117,  106,  115,
      106,  106,  106,  106,  106,  106,  106,  106,  116,  106,

      118,  106,  106,  106,  106,    0,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106
    } ;

static yyconst short int yy_nxt[257] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   32,   32,   32,   33,    8,
       34,   35,   32,   32,   32,   32,   32,   36,   37,   38,
       39,   41,   41,   44,   44,   45,   45,   50,   55,   42,
       42,   57,   60,   60,   69,   70,   61,   87,   56,   58,
       59,   62,   51,   64,   76,   65,   65,   63,   72,   73,
       46,   46,   81,  100,   66,   64,   67,   68,   68,   88,
       91,   77,   60,   60,   92,   92,   66,   64,   98,   65,
       65,   89,   97,   93,   94,  101,   94,   82,   66,   95,

       95,   83,   84,   85,   96,   96,   64,   91,   68,   68,
       92,   92,   96,   96,   95,   95,  102,   66,  102,   93,
       96,  103,  103,  104,   47,  104,   95,   95,  105,  105,
       96,   96,  100,  103,  103,  103,  103,   78,   96,   96,
      105,  105,  105,  105,   75,   71,   96,   54,   53,   49,
       48,   47,  106,  106,  101,   40,   40,   40,   40,   40,
       40,   43,   43,   43,   43,   43,   43,   52,  106,   52,
      106,   52,   52,   74,   74,   79,  106,  106,   79,   79,
       79,   80,  106,   80,   80,   80,   80,   86,  106,   86,
       86,   86,   86,   52,   52,   52,   90,   90,   90,   90,

       90,   90,   99,  106,   99,   99,   99,   99,   86,   86,
       86,   99,   99,   99,    7,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106
    } ;

static yyconst short int yy_chk[257] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    6,    5,    6,   14,   19,    3,
        4,   21,   22,   22,   28,   28,   23,   52,   19,   21,
       21,   23,   14,   24,   37,   24,   24,   23,   30,   30,
        5,    6,   46,   86,   24,   25,   24,   25,   25,   52,
       90,   37,   60,   60,   64,   64,   25,   65,   73,   65,
       65,   60,   69,   64,   66,   86,   66,   46,   65,   66,

       66,   46,   46,   46,   67,   67,   68,   62,   68,   68,
       92,   92,   67,   67,   94,   94,   89,   68,   89,   92,
       67,   89,   89,   93,   47,   93,   95,   95,   93,   93,
       96,   96,   99,  102,  102,  103,  103,   42,   96,   96,
      104,  104,  105,  105,   35,   29,   96,   18,   15,   13,
       11,    9,    7,    0,   99,  107,  107,  107,  107,  107,
      107,  108,  108,  108,  108,  108,  108,  109,    0,  109,
        0,  109,  109,  110,  110,  111,    0,    0,  111,  111,
      111,  112,    0,  112,  112,  112,  112,  113,    0,  113,
      113,  113,  113,  114,  114,  114,  115,  115,  115,  115,

      115,  115,  116,    0,  116,  116,  116,  116,  117,  117,
      117,  118,  118,  118,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106,  106,  106,  106,  106,
      106,  106,  106,  106,  106,  106
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#define INITIAL 0
#line 2 "lexer.l"
#include <cstdio>
#include <cstdarg>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>
#ifdef _WIN32
#  include <direct.h>
#  define make_dir(p) _mkdir(p)
#else
#  include <sys/stat.h>
#  define make_dir(p) mkdir((p), 0755)
#endif
#include "tokens.h"        // Defines TokenType enum
#include "symbol_table.h"  // Defines SymbolTable and SymbolEntry
int col_num = 1;
std::string str_buf;
int str_start_line;
int comment_start_line;   // line where the current /* comment opened

/* YY_USER_ACTION runs before every rule action.
   We use it to snapshot the current lexeme (yytext) for the token table.
   String literals override this later with the reconstructed full string. */
#define YY_USER_ACTION \
    token_start_col = col_num; \
    col_num += yyleng; \
    current_lexeme = yytext;

int token_start_col = 1;

/* ── Lexeme / error tracking globals ──────────────────────────────────────── */
std::string current_lexeme;            // set by YY_USER_ACTION; overridden for strings
std::vector<std::string> error_log;    // all collected error/warning messages
bool had_error = false;

void log_error(const char* format, ...) {
    char buffer[1024];
    va_list args;
    va_start(args, format);
    vsnprintf(buffer, sizeof(buffer), format, args);
    va_end(args);
    error_log.push_back(std::string(buffer));
    had_error = true;
}

/* ── Symbol table ─────────────────────────────────────────────────────────── */
SymbolTable symtab;
static const std::unordered_map<std::string, int> keywords = {
    {"if",        T_IF},       {"else",      T_ELSE},
    {"for",       T_FOR},      {"while",     T_WHILE},
    {"do",        T_DO},       {"until",     T_UNTIL},
    {"switch",    T_SWITCH},   {"case",      T_CASE},
    {"default",   T_DEFAULT},  {"break",     T_BREAK},
    {"continue",  T_CONTINUE}, {"goto",      T_GOTO},
    {"return",    T_RETURN},
    {"int",       T_INT},      {"char",      T_CHAR},
    {"float",     T_FLOAT},    {"double",    T_DOUBLE},
    {"void",      T_VOID},     {"static",    T_STATIC},
    {"struct",    T_STRUCT},   {"typedef",   T_TYPEDEF},
    {"enum",      T_ENUM},     {"union",     T_UNION},
    {"class",     T_CLASS},    {"public",    T_PUBLIC},
    {"private",   T_PRIVATE},  {"protected", T_PROTECTED},
    {"this",      T_THIS},     {"new",       T_NEW},
    {"delete",    T_DELETE},   {"virtual",   T_VIRTUAL},
    {"friend",    T_FRIEND}
};
/* keyword lookup table for all reserved words instead of providing separate lexer, we rely on a simple dictionary lookup*/


#define COMMENT 1

#define STRING 2

#line 564 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 89 "lexer.l"


    /* ── Multiline comments ─────────────────────────────────────────────── */
#line 719 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 107 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 215 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 92 "lexer.l"
{ comment_start_line = yylineno; BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 93 "lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "lexer.l"
{ col_num = 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 95 "lexer.l"
{ }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 96 "lexer.l"
{
                      log_error("Error: unterminated comment starting at line %d", comment_start_line);
                      yyterminate();
                  }
	YY_BREAK
case 5:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 101 "lexer.l"
{} /* Single-line comment — consume to end of line */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 102 "lexer.l"
{ col_num = 1; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 103 "lexer.l"
{}
	YY_BREAK
/* ── Multi-character operators ──────────────────────────────────────── */
case 8:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return T_LSHIFT_ASSIGN; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return T_RSHIFT_ASSIGN; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return T_PLUS_ASSIGN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return T_MINUS_ASSIGN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return T_MUL_ASSIGN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return T_DIV_ASSIGN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return T_MOD_ASSIGN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return T_AND_ASSIGN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return T_OR_ASSIGN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return T_XOR_ASSIGN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return T_LE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return T_GE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return T_EQ; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return T_NE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return T_AND; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return T_OR; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return T_INCR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return T_DECR; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return T_ARROW; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return T_LSHIFT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return T_RSHIFT; }
	YY_BREAK
/* ── Single-character operators and punctuation ─────────────────────── */
case 29:
YY_RULE_SETUP
#line 129 "lexer.l"
{ return T_PLUS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return T_MINUS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 131 "lexer.l"
{ return T_MUL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return T_DIV; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return T_MOD; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return T_LT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return T_GT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return T_ASSIGN; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return T_NOT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return T_BIT_AND; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return T_BIT_OR; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 140 "lexer.l"
{ return T_BIT_XOR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 141 "lexer.l"
{ return T_BIT_NOT; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return T_SEMICOLON; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return T_COMMA; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 144 "lexer.l"
{ return T_LBRACE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 145 "lexer.l"
{ return T_RBRACE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 146 "lexer.l"
{ return T_LPAREN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 147 "lexer.l"
{ return T_RPAREN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 148 "lexer.l"
{ return T_LBRACKET; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 149 "lexer.l"
{ return T_RBRACKET; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 150 "lexer.l"
{ return T_DOT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "lexer.l"
{ return T_QUESTION; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "lexer.l"
{ return T_COLON; }
	YY_BREAK
/* ── Integer literals ───────────────────────────────────────────────── */
/* Hex first (distinct 0x prefix); bare 0 accepted; multi-digit
       leading-zero is rejected as invalid/unsupported octal. */
case 53:
YY_RULE_SETUP
#line 157 "lexer.l"
{ return T_INT_CONST; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 158 "lexer.l"
{ log_error("Error: Invalid Octal literal at line %d", yylineno); return T_ERROR; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 159 "lexer.l"
{ return T_INT_CONST; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 160 "lexer.l"
{ return T_INT_CONST; }
	YY_BREAK
/* ── Float literals ─────────────────────────────────────────────────── */
/* Valid forms: 1.0  1.  .1  1e10  2.5e-3  .5e+2
       BAD_EXP rules fire only when no digits follow [eE][+-]? */
case 57:
YY_RULE_SETUP
#line 165 "lexer.l"
{ return T_FLOAT_CONST; }  /* 1., 1.0, 1.0e10 */
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 166 "lexer.l"
{ return T_FLOAT_CONST; }  /* .1, .1e10 */
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 167 "lexer.l"
{ return T_FLOAT_CONST; }  /* 1e10 */
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 169 "lexer.l"
{ log_error("Error: malformed scientific notation at line %d", yylineno); return T_ERROR; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 170 "lexer.l"
{ log_error("Error: malformed scientific notation at line %d", yylineno); return T_ERROR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 171 "lexer.l"
{ log_error("Error: malformed scientific notation at line %d", yylineno); return T_ERROR; }
	YY_BREAK
/* ── Char literals ──────────────────────────────────────────────────── */
/* Supported escapes: \n \t \r \\ \' \" \a \b \f \v \0               */
case 63:
YY_RULE_SETUP
#line 175 "lexer.l"
{ return T_CHAR_CONST; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 176 "lexer.l"
{ log_error("Error: multi-character char literal at line %d", yylineno); return T_ERROR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 177 "lexer.l"
{ log_error("Error: unterminated char literal at line %d", yylineno); return T_ERROR; }
	YY_BREAK
/* ── String literals (exclusive STRING state) ────────────────────────── */
case 66:
YY_RULE_SETUP
#line 180 "lexer.l"
{
                        str_buf.clear();
                        str_start_line = yylineno;
                        BEGIN(STRING);
                    }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 186 "lexer.l"
{
                        /* Override the lexeme set by YY_USER_ACTION with the
                           full reconstructed quoted string. */
                        current_lexeme = "\"" + str_buf + "\"";
                        BEGIN(INITIAL);
                        return T_STRING_LITERAL;
                    }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 194 "lexer.l"
{ str_buf += '\n'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 195 "lexer.l"
{ str_buf += '\t'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 196 "lexer.l"
{ str_buf += '\r'; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 197 "lexer.l"
{ str_buf += '\\'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 198 "lexer.l"
{ str_buf += '"';  }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 200 "lexer.l"
{
                        log_error("Warning: unknown escape '\\%c' in string at line %d", yytext[1], yylineno);
                        str_buf += yytext[1];
                    }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 205 "lexer.l"
{
                        log_error("Error: unterminated string literal starting at line %d", str_start_line);
                        col_num = 1;               /* reset column — YY_USER_ACTION already incremented it */
                        BEGIN(INITIAL);
                        return T_ERROR;
                    }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 212 "lexer.l"
{ str_buf += yytext; }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 214 "lexer.l"
{
                        log_error("Error: unterminated string literal starting at line %d", str_start_line);
                        yyterminate();
                    }
	YY_BREAK
/* ── Identifiers and keywords ─────────────────────────────────────── */
case 76:
YY_RULE_SETUP
#line 220 "lexer.l"
{
    auto it = keywords.find(yytext);
    if (it != keywords.end()) {
        return it->second;
    }
    symtab.insert(yytext, T_IDENTIFIER, yylineno);
    return T_IDENTIFIER;
}
	YY_BREAK
/* ── Catch-all for illegal characters ──────────────────────────────── */
case 77:
YY_RULE_SETUP
#line 230 "lexer.l"
{
                      log_error("Error: unexpected character '%s' at line %d", yytext, yylineno);
                      return T_ERROR;
                  }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 235 "lexer.l"
ECHO;
	YY_BREAK
#line 1258 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 107 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 107 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 106);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 235 "lexer.l"


int yywrap() { return 1; }

/* ════════════════════════════════════════════════════════════════════════════
   main()
   ──────
   Reads one source file (or stdin), lexes it, then writes three output files
   under out/ (created if missing):

     out/token_stream_<stem>.txt   — two-column table: Lexeme | Token
     out/symbol_table_<stem>.txt   — identifier symbol table
     out/error_log_<stem>.txt      — all collected errors / warnings

   Exits 0 if no errors, 1 if any lexical error was found.
   ════════════════════════════════════════════════════════════════════════════ */
int main(int argc, char** argv) {
    FILE* input_file   = nullptr;
    int   file_arg_idx = 1;

    /* Legacy flag kept for backward compatibility */
    if (argc >= 2 && std::string(argv[1]) == "--symbol-table") {
        file_arg_idx = 2;
    }

    /* ── Open input ──────────────────────────────────────────────────────── */
    std::string stem = "stdin";
    if (argc >= file_arg_idx + 1) {
        input_file = std::fopen(argv[file_arg_idx], "r");
        if (!input_file) {
            std::perror("Unable to open input file");
            return 1;
        }
        yyin = input_file;

        /* Extract stem: strip directory path and file extension.
           e.g.  "../tests/valid_basic.c"  →  "valid_basic"           */
        std::string path = argv[file_arg_idx];
        auto slash = path.find_last_of("/\\");
        std::string base = (slash != std::string::npos) ? path.substr(slash + 1) : path;
        auto dot = base.rfind('.');
        stem = (dot != std::string::npos) ? base.substr(0, dot) : base;
    } else {
        yyin = stdin;
    }

    /* ── Create out/ directory ───────────────────────────────────────────── */
    make_dir("out");   /* silently ignored if already exists */

    const std::string ts_path  = "out/token_stream_"  + stem + ".txt";
    const std::string sym_path = "out/symbol_table_"  + stem + ".txt";
    const std::string err_path = "out/error_log_"     + stem + ".txt";

    /* ── Lex the entire file, collect valid tokens ───────────────────────── */
    struct TokenRecord { std::string lexeme; int tok; };
    std::vector<TokenRecord> tokens;
    int tok;
    while ((tok = yylex()) != T_EOF) {
        if (tok == T_ERROR) continue;
        tokens.push_back({ current_lexeme, tok });
    }

    /* ── Write token_stream file ─────────────────────────────────────────── */
    {
        std::ofstream ts(ts_path);
        if (had_error) {
            ts << "NOTE: Lexical errors were found. Token stream may be incomplete.\n";
            ts << "      See: " << err_path << "\n\n";
        }
        /* Two-column table */
        ts << std::left << std::setw(28) << "Lexeme" << "Token\n";
        ts << std::string(48, '-') << "\n";
        for (auto& r : tokens) {
            /* Use the existing operator<< from tokens.h to get the real enum name. */
        std::ostringstream tname;
        tname << static_cast<TokenType>(r.tok);
        ts << std::left << std::setw(28) << r.lexeme
           << tname.str() << "\n";
        }
    }

    /* ── Write symbol_table file ─────────────────────────────────────────── */
    {
        std::ofstream sym(sym_path);
        symtab.print(sym);
    }

    /* ── Write error_log file ────────────────────────────────────────────── */
    {
        std::ofstream err(err_path);
        if (error_log.empty()) {
            err << "No lexical errors.\n";
        } else {
            for (auto& msg : error_log) {
                err << msg << "\n";
            }
        }
    }

    /* ── Console summary (brief) ─────────────────────────────────────────── */
    if (had_error) {
        std::cerr << "[ERRORS] " << error_log.size() << " error(s) in '"
                  << stem << "'. See " << err_path << "\n";
    } else {
        std::cout << "[OK] " << tokens.size() << " token(s) in '"
                  << stem << "'. Output: " << ts_path << "\n";
    }

    if (input_file) std::fclose(input_file);
    return had_error ? 1 : 0;
}
